import Link from "next/link";
import { prisma } from "@/lib/db";

function money(v: number) { return new Intl.NumberFormat("en-AE", { style: "currency", currency: "AED", maximumFractionDigits: 0 }).format(v); }

export default async function SettlementsPage() {
  const trips = await prisma.trip.findMany({ include: { customer: true, driver: true, cashAdvances: true, expenses: true, settlement: true }, orderBy: { tripDate: "desc" } });
  return <div className="space-y-5"><div><h1 className="text-2xl font-black text-slate-950">Trip Settlements</h1><p className="text-sm text-slate-500">Close trips by comparing cash given against actual driver receipts.</p></div><div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="p-3">Trip</th><th className="p-3">Driver</th><th className="p-3 text-right">Cash</th><th className="p-3 text-right">Expenses</th><th className="p-3 text-right">Balance</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{trips.map(t => { const cash = t.cashAdvances.reduce((s,c)=>s+Number(c.amount),0); const exp = t.expenses.reduce((s,e)=>s+Number(e.amount || 0),0); const bal = cash-exp; return <tr key={t.id} className="hover:bg-slate-50"><td className="p-3 font-bold">{t.tripNo || t.tripNumber}<div className="text-xs text-slate-500">{t.customer.companyName || t.customer.name}</div></td><td className="p-3">{t.driver.name}</td><td className="p-3 text-right font-black">{money(cash)}</td><td className="p-3 text-right font-black">{money(exp)}</td><td className="p-3 text-right font-black">{money(bal)}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{t.settlement?.status || "PENDING"}</span></td><td className="p-3"><Link className="text-xs font-bold text-emerald-700" href={`/trip-settlements/${t.id}`}>Open</Link></td></tr>})}</tbody></table></div></div>;
}
