import { createVehicle, updateVehicle } from "@/lib/master-data";

function dateValue(value?: Date | string | null) {
  return value ? new Date(value).toISOString().slice(0, 10) : "";
}

export default function VehicleForm({ vehicle, drivers }: { vehicle?: any; drivers: { id: string; name: string }[] }) {
  const action = vehicle?.id ? updateVehicle.bind(null, vehicle.id) : createVehicle;
  const input = "rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-emerald-500";
  return <form action={action} className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2"><label className="grid gap-1 text-sm font-bold text-slate-700">Truck No<input className={input} name="truckNo" defaultValue={vehicle?.truckNo || ""} required /></label><label className="grid gap-1 text-sm font-bold text-slate-700">Plate No<input className={input} name="plateNo" defaultValue={vehicle?.plateNo || ""} required /></label><label className="grid gap-1 text-sm font-bold text-slate-700">Trailer No<input className={input} name="trailerNo" defaultValue={vehicle?.trailerNo || ""} /></label><label className="grid gap-1 text-sm font-bold text-slate-700">Model<input className={input} name="model" defaultValue={vehicle?.model || ""} /></label><label className="grid gap-1 text-sm font-bold text-slate-700">Vehicle Type<select className={input} name="vehicleType" defaultValue={vehicle?.vehicleType || "TRUCK"}>{["TRUCK","TRAILER","TANKER","FLATBED","REEFER","WATER_TANKER","OTHER"].map(v => <option key={v} value={v}>{v.replace("_", " ")}</option>)}</select></label><label className="grid gap-1 text-sm font-bold text-slate-700">Owner Type<select className={input} name="ownerType" defaultValue={vehicle?.ownerType || "COMPANY_OWNED"}>{["COMPANY_OWNED","RENTED","THIRD_PARTY"].map(v => <option key={v} value={v}>{v.replace("_", " ")}</option>)}</select></label><label className="grid gap-1 text-sm font-bold text-slate-700">Registration Expiry<input className={input} type="date" name="registrationExpiry" defaultValue={dateValue(vehicle?.registrationExpiry)} required /></label><label className="grid gap-1 text-sm font-bold text-slate-700">Insurance Expiry<input className={input} type="date" name="insuranceExpiry" defaultValue={dateValue(vehicle?.insuranceExpiry)} required /></label><label className="grid gap-1 text-sm font-bold text-slate-700">Current Driver<select className={input} name="currentDriverId" defaultValue={vehicle?.currentDriverId || ""}><option value="">Unassigned</option>{drivers.map((driver) => <option key={driver.id} value={driver.id}>{driver.name}</option>)}</select></label><label className="grid gap-1 text-sm font-bold text-slate-700">Status<select className={input} name="status" defaultValue={vehicle?.status || "AVAILABLE"}>{["AVAILABLE","ON_TRIP","MAINTENANCE","INACTIVE"].map(v => <option key={v} value={v}>{v.replace("_", " ")}</option>)}</select></label><div className="md:col-span-2"><button className="rounded-lg bg-emerald-600 px-5 py-2 text-sm font-bold text-white hover:bg-emerald-700">Save Vehicle</button></div></form>;
}
